### ISSUE TITLE
Small UI improvements

### ISSUE THREAD

**Issue by rayrutjes** [pixelastic/parisweb#1]
Demo looks awesome!

Here are very small UI tweak suggestions:
- `.hit--author {font-weight: bold;}`
- `.hit--tag {font-weight: bold;}`

Also on mobile, you should probably adjust the line-height of the author when it is broken into 2 lines.

**Comment by pixelastic** [comment]
I've updated the author and tag display (I actually put the tags in italic, bold was too strong in my opinion).

Would you have a screenshot of the issue with the author on mobile? Here is what I have and it feels fine to me:
![image](https://cloud.githubusercontent.com/assets/283419/18244255/5a21d616-735f-11e6-84a5-20e247712e14.png)

**Comment by rayrutjes** [comment]
I think you fixed it somehow @pixelastic, can not re-produce it! Nice changes! Closing this ;)
