### ISSUE TITLE
Filter with slides/video

### ISSUE THREAD

**Issue by DelphineM** [pixelastic/parisweb#4]
Hello,
Thanks a lot for this tool.

I have an idea: adding a filter if we only want to see results with a video or with slides.

**Comment by pixelastic** [comment]
Great idea, I'll see to add that.

**Comment by pixelastic** [comment]
Feature added:
![image](https://cloud.githubusercontent.com/assets/283419/18832933/69c51070-83ee-11e6-9f4a-f6bdf1bd3ab5.png)

https://pixelastic.github.io/parisweb/ :)
